# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-20 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarantineTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinedata',
            name='QuarantineName',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
