# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarantineTest', '0003_auto_20190320_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerregistry',
            name='ContactNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quarantineregistry',
            name='ContactNo_Quar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
