# Generated by Django 2.1.7 on 2019-03-17 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.CharField(max_length=20)),
                ('CompanyName', models.CharField(max_length=50)),
                ('CorporateIDNo', models.CharField(max_length=20)),
                ('CorporateContactNo', models.BigIntegerField()),
                ('RegisterTime', models.DateTimeField()),
                ('OperatingPlace', models.CharField(max_length=50)),
                ('OperatingKind', models.IntegerField()),
                ('InvestigateRes', models.BooleanField()),
                ('BLicenseRegisterNo', models.CharField(max_length=20)),
                ('BLicenseSrc', models.CharField(max_length=100)),
                ('BLicenseDeadline', models.DateTimeField()),
                ('PLicenseNo', models.CharField(max_length=20)),
                ('PLicenseSrc', models.CharField(max_length=100)),
                ('PLicenseDeadline', models.DateTimeField()),
                ('AEPCertificateNo', models.CharField(max_length=20)),
                ('AEPCertificateSrc', models.CharField(max_length=100)),
                ('TaxRCNo', models.CharField(max_length=20)),
                ('TaxRCSrc', models.CharField(max_length=100)),
                ('FoodDistributionLicenseNo', models.CharField(max_length=20)),
                ('FoodDistributionLicenseSrc', models.CharField(max_length=100)),
                ('FoodHygienePermitNo', models.CharField(max_length=20)),
                ('FoodHygienePermitSrc', models.CharField(max_length=100)),
                ('OrganizationCodeCertificateNo', models.CharField(max_length=20)),
                ('OrganizationCodeCertificateSrc', models.CharField(max_length=100)),
                ('RoadTransportBusinessLicenseNo', models.CharField(max_length=20)),
                ('RoadTransportBusinessLicenseSrc', models.CharField(max_length=100)),
                ('AnimalEpidemicPCNo', models.CharField(max_length=20)),
                ('AnimalEpidemicPCSrc', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsumerId', models.CharField(max_length=15)),
                ('ConsumerName', models.CharField(max_length=10)),
                ('ContactNo', models.IntegerField()),
                ('RegisterTimeConsumer', models.DateField(default=datetime.date(2019, 3, 17))),
                ('SearchCounts', models.IntegerField(default=0)),
                ('VIP', models.BooleanField(default=False)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SellData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellID', models.CharField(max_length=20)),
                ('ProductionID', models.CharField(max_length=20)),
                ('SellLocation', models.CharField(max_length=50)),
                ('SPReceiveTime', models.DateTimeField()),
                ('SPSelloutTime', models.DateTimeField(default=None)),
                ('Price', models.IntegerField()),
                ('APApprovalRes', models.IntegerField(default=0)),
                ('AccountabilityFlag', models.IntegerField(default=0)),
                ('SellUCLLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sell2.ConsumerRegistry')),
                ('SellerID', models.CharField(max_length=20)),
                ('SellerName', models.CharField(max_length=10)),
                ('IDNo', models.CharField(max_length=20)),
                ('RegisterTime', models.DateTimeField()),
                ('WorkPlaceID', models.CharField(max_length=50)),
                ('PhotoSrc', models.CharField(max_length=100)),
            ],
            bases=('Sell2.consumerregistry',),
        ),
    ]
