# Generated by Django 2.1.7 on 2019-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Total', '0002_auto_20190302_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellID', models.BigIntegerField()),
                ('ProductionID', models.BigIntegerField()),
                ('SellLocation', models.CharField(max_length=50)),
                ('SPReceiveTime', models.DateTimeField()),
                ('SPSelloutTime', models.DateTimeField(default=None)),
                ('Price', models.IntegerField()),
                ('APApprovalRes', models.IntegerField(default=0)),
                ('AccountabilityFlag', models.IntegerField(default=0)),
                ('SellUCLLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerID', models.IntegerField()),
                ('SellName', models.CharField(max_length=10)),
                ('IDNo', models.BigIntegerField()),
                ('ContactNo', models.BigIntegerField()),
                ('RegisterTime', models.DateTimeField()),
                ('WorkPlaceID', models.CharField(max_length=50)),
                ('PhotoSrc', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
