# Generated by Django 2.1.7 on 2019-03-25 07:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsumerId', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('ConsumerName', models.CharField(blank=True, max_length=10, null=True)),
                ('ContactNo', models.CharField(max_length=11)),
                ('RegisterTimeConsumer', models.DateField(default=datetime.date.today)),
                ('SearchCounts', models.IntegerField(default=0)),
                ('VIP', models.BooleanField(default=False)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('CharacterFlag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProcessID', models.CharField(blank=True, max_length=22, null=True, unique=True)),
                ('ProductionID', models.CharField(max_length=10)),
                ('ProcessPersonID', models.CharField(max_length=10)),
                ('ProcessLocation', models.CharField(max_length=7)),
                ('ProcessTime', models.DateField(default=datetime.date.today)),
                ('ProductionKind', models.IntegerField()),
                ('ReproductionID1', models.CharField(max_length=10)),
                ('ReproductionID2', models.CharField(max_length=10)),
                ('ReproductionID3', models.CharField(max_length=10)),
                ('ReproductionID4', models.CharField(max_length=10)),
                ('ReproductionID5', models.CharField(max_length=10)),
                ('ProcessUCLLink', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process.ConsumerRegistry')),
                ('IDNo', models.CharField(max_length=18)),
                ('WorkPlaceID', models.CharField(max_length=50)),
                ('PhotoSrc', models.CharField(blank=True, max_length=100, null=True)),
                ('HC4foodCertificationNo', models.BigIntegerField()),
                ('HC4foodCertificationSrc', models.CharField(max_length=50)),
                ('ProcessorCounts', models.IntegerField(default=0)),
            ],
            bases=('process.consumerregistry',),
        ),
    ]
