# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-24 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trance_produce',
        ),
        migrations.DeleteModel(
            name='TransportData',
        ),
    ]
