# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-24 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20190324_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='trance_produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductionID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(max_length=50)),
                ('BatchNum', models.IntegerField(default=0)),
                ('ProductionID', models.CharField(max_length=50)),
                ('TransactionPersonID', models.CharField(default='', max_length=50)),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('Flag', models.CharField(max_length=50)),
                ('TransactionStartTime', models.DateField(default=datetime.date.today)),
                ('TransactionEndTime', models.DateField(default=datetime.date.today)),
                ('TransactionStartUCLLink', models.CharField(max_length=50)),
                ('TransactionEndUCLLink', models.CharField(max_length=50)),
            ],
        ),
    ]
