# Generated by Django 2.1.7 on 2019-03-13 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyId', models.CharField(max_length=15)),
                ('CompanyName', models.CharField(max_length=40)),
                ('CorporateName', models.CharField(max_length=10)),
                ('CorporateIDNo', models.BigIntegerField()),
                ('RegisterTime', models.DateField()),
                ('OperatingPlace', models.CharField(max_length=30)),
                ('OperatingKind', models.IntegerField()),
                ('InvestigateRes', models.IntegerField()),
                ('BLicenseRegisterNo', models.BigIntegerField()),
                ('BLicenseSrc', models.CharField(max_length=50)),
                ('BLicenseDeadline', models.DateField()),
                ('PLicenseNo', models.CharField(max_length=30)),
                ('PLicenseSrc', models.CharField(max_length=40)),
                ('PLicenseDeadline', models.DateField()),
                ('AEPCertificateNo', models.BigIntegerField()),
                ('AEPCertificateSrc', models.CharField(max_length=40)),
                ('TaxRCNo', models.BigIntegerField()),
                ('TaxRCSrc', models.CharField(max_length=50)),
                ('FoodDistributionLicenseNo', models.BigIntegerField()),
                ('FoodDistributionLicenseSrc', models.CharField(max_length=50)),
                ('FoodHygienePermitNo', models.BigIntegerField()),
                ('FoodHygienePermitSrc', models.CharField(max_length=50)),
                ('OrganizationCodeCertificateNo', models.BigIntegerField()),
                ('OrganizationCodeCertificateSrc', models.CharField(max_length=50)),
                ('RoadTransportBusinessLicenseNo', models.BigIntegerField()),
                ('RoadTransportBusinessLicenseSrc', models.CharField(max_length=50)),
                ('AnimalEpidemicPCNo', models.BigIntegerField()),
                ('AnimalEpidemicPCSrc', models.CharField(max_length=50)),
                ('SecretKeys', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsumerId', models.CharField(max_length=15)),
                ('ConsumerName', models.CharField(max_length=10)),
                ('ContactNo', models.BigIntegerField()),
                ('RegisterTimeConsumer', models.DateField(default=datetime.date.today)),
                ('SearchCounts', models.IntegerField(default=0)),
                ('VIP', models.BooleanField(default=False)),
                ('Password', models.CharField(max_length=30)),
                ('CharacterFlag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordID', models.CharField(max_length=30)),
                ('MonitorId', models.BigIntegerField()),
                ('State', models.IntegerField()),
                ('HealthState', models.SmallIntegerField()),
                ('GPSLocation', models.CharField(max_length=50)),
                ('ActiveDis', models.FloatField()),
                ('Weight', models.FloatField()),
                ('BodyTemperature', models.FloatField()),
                ('UCLLink', models.CharField(max_length=50)),
                ('MonitorRecordTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNo', models.CharField(max_length=18)),
                ('RegisterTime', models.CharField(max_length=30)),
                ('WorkPlaceID', models.CharField(max_length=10)),
                ('PhotoSrc', models.CharField(blank=True, max_length=100, null=True)),
                ('CertificateNo', models.CharField(blank=True, max_length=32, null=True)),
                ('CertificateSrc', models.CharField(blank=True, max_length=100, null=True)),
                ('LicensedVeterinaryQCNo', models.CharField(blank=True, max_length=32, null=True)),
                ('LicensedVeterinaryQCSrc', models.CharField(blank=True, max_length=32, null=True)),
                ('QuarantineCounts', models.IntegerField(default=0)),
            ],
            managers=[
                ('inherit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ConsumerRegistry')),
                ('IDNo', models.BigIntegerField()),
                ('RegisterTime', models.DateField()),
                ('WorkPlaceID', models.CharField(max_length=50)),
                ('PhotoSrc', models.CharField(max_length=50)),
                ('HC4foodCertificationNo', models.BigIntegerField()),
                ('HC4foodCertificationSrc', models.CharField(max_length=50)),
                ('ProcessorCounts', models.IntegerField(default=0)),
            ],
            bases=('app.consumerregistry',),
            managers=[
                ('inherit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProducerRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ConsumerRegistry')),
                ('IDNo', models.BigIntegerField()),
                ('RegisterTime', models.DateField()),
                ('ProductionPlace', models.CharField(max_length=30)),
                ('ProductionKind', models.IntegerField()),
                ('ProductionScale', models.CharField(max_length=100)),
                ('InvestigateRes', models.IntegerField()),
                ('SecretKeys', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=15)),
                ('companyregistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='app.CompanyRegistry')),
            ],
            bases=('app.consumerregistry',),
            managers=[
                ('inherit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SellerRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ConsumerRegistry')),
                ('IDNo', models.BigIntegerField()),
                ('RegisterTime', models.DateTimeField()),
                ('WorkPlaceID', models.CharField(max_length=50)),
                ('PhotoSrc', models.CharField(max_length=100)),
            ],
            bases=('app.consumerregistry',),
            managers=[
                ('inherit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TransporterRegistry',
            fields=[
                ('consumerregistry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ConsumerRegistry')),
                ('IDNo', models.BigIntegerField()),
                ('RegisterTime', models.DateField()),
                ('WorkPlaceID', models.CharField(max_length=30)),
                ('PhotoSrc', models.CharField(max_length=40)),
                ('RoadTransportQCNo', models.BigIntegerField()),
                ('RoadTransportQCSrc', models.CharField(max_length=40)),
                ('TransportCounts', models.IntegerField(default=0)),
            ],
            bases=('app.consumerregistry',),
            managers=[
                ('inherit', django.db.models.manager.Manager()),
            ],
        ),
    ]
