# Generated by Django 2.1.7 on 2019-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerregistry',
            name='imgID',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='producerregistry',
            name='imgwork',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
