# Generated by Django 2.1.7 on 2019-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190321_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerregistry',
            name='InvestigateRes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producerregistry',
            name='ProductionKind',
            field=models.IntegerField(default=0),
        ),
    ]
